version: '3'
services:
  mysql:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: vizion
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
